### ISSUE TITLE
Looks like I need some more packages installed to work

### ISSUE THREAD

**Issue by jonhilgart22** [Thomas-Boi/heroku-python-playwright-chromium#3]
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     sudo playwright install-deps                     ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     sudo apt-get install libatk1.0-0\                ║
║         libatk-bridge2.0-0\                          ║
║         libdrm2\                                     ║
║         libxkbcommon0\                               ║
║         libxcomposite1\                              ║
║         libxdamage1\                                 ║
║         libxfixes3\                                  ║
║         libxrandr2\                                  ║
║         libgbm1\                                     ║
║         libasound2\                                  ║
║         libatspi2.0-0                                ║
║                                                      ║
║ <3 Playwright Team

**Comment by Thomas-Boi** [comment]
Hi @jonhilgart22 ,

Just to double check, did you add the 3rd party buildpack yet?

![image](https://github.com/user-attachments/assets/e5f999b2-cd02-4550-8f13-0a008e08b55d)

**Comment by jonhilgart22** [comment]
I ended up just building with a Dockerfile because my slug was too large. Thanks!
